# syntax=docker/dockerfile:1.7
FROM golang:1.21-alpine

RUN apk add --no-cache ca-certificates postgresql-client

WORKDIR /app

RUN --mount=type=cache,target=/go/pkg/mod \
	--mount=type=cache,target=/root/.cache/go-build \
	go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

COPY migrations ./migrations
COPY scripts/run-migrations.sh /app/run-migrations.sh
RUN chmod +x /app/run-migrations.sh

ENV PATH="/go/bin:${PATH}"

CMD ["sh", "/app/run-migrations.sh"]