apiVersion: v1
kind: Secret
metadata:
  name: locker-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: change-me
  YOOKASSA_SHOP_ID: ""
  YOOKASSA_API_KEY: ""
